spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: false
      max-file-size: 2GB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-wudhz82h5x4aqyt8.us.auth0.com/
auth0:
  audience: https://catalog.interview.spscommerce.com
import:
  location: ./import-files
  fileTypes:
    - csv
    - xlsx
rate-limits:
  requests: 10
  duration: 1
  timeUnit: MINUTE

